web:
  build: .
  ports:
    - "80:80"
  command: mix phx.server
  environment:
    - MIX_ENV=prod
    - PORT=80
    - MAILGUN_API_KEY=key-00000000000000000000000000000000
    - MAILGUN_DOMAIN=example.com
    - URL_DOMAIN=example.com
    - URL_PORT=80
  volumes:
    - .:/app
  links:
    - db
dev:
  build: .
  ports:
    - "4000:4000"
  command: mix phx.server
  environment:
    - MIX_ENV=dev
    - PORT=4000
    - URL_DOMAIN=example.com
    - URL_PORT=4000
  volumes:
    - .:/app
  links:
    - db
db:
  image: postgres:9.6
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db
  volumes:
    - pgdata:/var/lib/postgresql/data
