#!/bin/bash
docker-compose run web mix deps.get
docker-compose run web mix deps.compile
docker-compose run web mix ecto.create
docker-compose run web mix ecto.migrate
docker-compose run web mix create_secrets
docker-compose run web npm install
docker-compose run web ./node_modules/.bin/webpack -p
docker-compose run web mix phx.digest
docker-compose down
